### ISSUE TITLE
WebView里的输入框调起输入法的问题

### ISSUE THREAD

**Issue by choucai** [llfer2006/NestLayout#1]
你重写onTouchEvent方法后，当WebView里面有输入框的时候，调不起输入法。确定了时触摸事件的问题

**Comment by llfer2006** [comment]
抱歉，好久没看。
跟据你说的问题我看了一下，这并不是触摸事件的问题，而是WebView没有获得焦点的问题，你可以
调用webView.setFocusableInTouchMode(true)方法来解决无法输入的问题.
