### ISSUE TITLE
跟CollapsingToolbarLayout 一起工作时不能实现视差滚动的效果

### ISSUE THREAD

**Issue by jyh149129** [llfer2006/NestLayout#3]
当NestedWebView滚动时（app:layout_behavior="@string/appbar_scrolling_view_behavior"），顶部CollapsingToolbarLayout没有滚动效果

**Comment by llfer2006** [comment]
@jyh149129 是不是用的1.0的版本，最新版本没有这类问题，你可以看example中的DesignActivity的效果

**Comment by jyh149129** [comment]
好的，谢谢
